### ISSUE TITLE
🎈 Roadmap: Future Features & Ideas

### ISSUE THREAD

**Issue by kangarko** [kangarko/Puncher#8]
<h3><p align="center">A List of New Features and Ideas for Future Updates </p></h3>

## Want to suggest a feature?
* In order to stay high performance and to its original concept, please **only suggest features related to Puncher's kind of game**. 
* If you have a feature request, please **open a new ticket**.

## High priority
- [ ] Setup a test server

## Normal priority
- [ ] Reward for the first place even when only 1 player played.
- [ ] Sidebar: sort teams by order
- [ ] Team balancer and limiter
- [ ] Configurable explosion force
- [ ] Show selected team/class in sidebar and/or menu
- [ ] Flood with water / lava (?)
- [ ] Kill when in water

**Feel free to comment below, but comments are cleaned regularly to keep this page clean.**
